parameters:
#    object.example.class: Amateur\ObjectBundle\Example

services:
#    object.example:
#        class: %object.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
