Xtending\EntityBundle\Entity\Corporaciones:
    type: entity
    table: corporaciones
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator: { strategy: AUTO }
        nombre:
            type: string
            length: 255
            fixed: false
            nullable: true
    oneToMany:
        entidades:
            targetEntity: Entidades
            mappedBy: corporacion
            cascade:      [persist]
        contactos:
            targetEntity: Contactos
            mappedBy: corporacion
            cascade:      [persist]
        
    lifecycleCallbacks: {  }
