Xtending\EntityBundle\Entity\FormulariosResultadosHistorial:
    type: mappedSuperclass
    table: formularios_resultados_historial
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 250
            fixed: false
            nullable: true
        fechaautomatica:
            type: date
            nullable: true
            column: fechaAutomatica
        fechamanual:
            type: string
            length: 250
            fixed: false
            nullable: true         
        estado:
            type: string
            length: 250
            fixed: false
            nullable: true
        modificadoPor:
            type: string
            length: 250
            fixed: false
            nullable: false
            column: modificado_por
        fechaModificado:
            type: date
            nullable: false
            column: fecha_modificado
        comentario:
            type: string
            length: 2000
            fixed: false
            nullable: true
        version:
            type: integer
            length: 100
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
    manyToOne:
        formulariosDefiniciones:
            targetEntity: FormulariosDefiniciones
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                formularios_definiciones_id:
                    referencedColumnName: id
            orphanRemoval: false
        contacto:
            targetEntity: Contactos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contacto_id:
                    referencedColumnName: id
            orphanRemoval: false
        proveedor:
            targetEntity: Entidades
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                proveedor_id:
                    referencedColumnName: id
            orphanRemoval: false
        compartido:
            targetEntity: AsignacionIndividual
            joinColumns:
                asig_ind_id:
                    referencedColumnName: id
            orphanRemoval: false
        site:
            targetEntity: Sites
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                site_id:
                    referencedColumnName: id
            orphanRemoval: false
        empresa:
            targetEntity: Entidades
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                entidad_id:
                    referencedColumnName: id
            orphanRemoval: false
        formularioResultado:
            targetEntity: FormulariosResultados
            inversedBy: formulariosResultadosHistorial
            joinColumns:
                formulario_resultado_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        labelsCaratulaValor:
            targetEntity: LabelCaratulaValorHistorial
            mappedBy: formularioResultado
            cascade:      [persist]
        preguntasValor:
            targetEntity: PreguntaValorHistorial
            mappedBy: formulariosResultados
            cascade:      [persist]
        labelsCaratulaFile:
            targetEntity: FilesRegistro
            mappedBy: formularioResultado
            cascade:      [persist]
        
        accionesCorrectivas:
            targetEntity: AccionCorrectiva
            mappedBy: formularioResultado
            cascade:      [persist]
        formulariosResultadosHistorial:
            targetEntity: FormulariosResultadosHistorial
            mappedBy: formularioResultado
            cascade:      [persist]
        

    