Xtending\EntityBundle\Entity\PreguntaValor:
    type: entity
    table: preguntas_valor
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        textarea:
            type: string
            length: 5000
            fixed: false
            nullable: true
            column: textarea
        fecha:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: fecha
        text:
            type: string
            length: 50
            column: text
        archivo:
            type: string
            length: 100
            column: archivo
        
    oneToOne:
        pregunta:
            targetEntity: Preguntas
            joinColumns:
              id_pregunta:
                referencedColumnName: id
        criterioSeleccion:
            targetEntity: LabelsCriterio
            joinColumns:
              criterio_seleccion:
                referencedColumnName: id       
    manyToOne:
        formulariosResultados:
            targetEntity: FormulariosResultados
            inversedBy: preguntasValor
            joinColumns:
                formularios_resultados_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
