Amateur\ObjectBundle\Entity\Photo:
    type: entity
    table: photo
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 1000
            fixed: false
            nullable: true
        path:
            type: string
            length: 2000
            fixed: false
            nullable: true
        description:
            type: string
            length: 5000
            fixed: false
            nullable: true
        organizerId:
            type: integer
            unsigned: false
            nullable: false
            column: organizer_id
        userId:
            type: integer
            unsigned: false
            nullable: false
            column: user_id
        eventId:
            type: integer
            unsigned: false
            nullable: false
            column: event_id
    lifecycleCallbacks: {  }
