parameters:
#    news_user.example.class: Amateur\NewsUserBundle\Example

services:
#    news_user.example:
#        class: %news_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
