parameters:
#    entity.example.class: Xtending\EntityBundle\Example

services:
#    entity.example:
#        class: %entity.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
